/*
 * Lab 9, Exercise 1
 *
 * Question: Write a C program to generate the Fibonacci series using threads.
 * The parent thread will create a child thread that will generate the Fibonacci
 * numbers. The parent thread will wait and print the series generated by the
 * child thread.
 *
 */
#include <pthread.h>
#include <stdio.h>
#include <stdlib.h>

// Shared data structure to hold the Fibonacci sequence
typedef struct {
  long long *sequence;
  int count;
} fib_data;

// Function to be executed by the child thread
void* generate_fibonacci(void* param) {
  fib_data* data = (fib_data*)param;
  int count = data->count;

  if (count <= 0) {
    pthread_exit(0);
  }

  data->sequence = malloc(count * sizeof(long long));
  if (data->sequence == NULL) {
    perror("Failed to allocate memory for sequence");
    pthread_exit(0);
  }

  // Generate Fibonacci numbers
  if (count > 0) {
    data->sequence[0] = 0;
  }
  if (count > 1) {
    data->sequence[1] = 1;
  }
  for (int i = 2; i < count; i++) {
    data->sequence[i] = data->sequence[i - 1] + data->sequence[i - 2];
  }

  pthread_exit(0);
}

int main(int argc, char *argv[]) {
  if (argc != 2) {
    fprintf(stderr, "Usage: %s <number_of_fibonacci_numbers>\n", argv[0]);
    return 1;
  }

  int num_fib = atoi(argv[1]);
  if (num_fib < 0) {
    fprintf(stderr, "Please enter a non-negative number.\n");
    return 1;
  }

  pthread_t thread;
  fib_data data;
  data.count = num_fib;
  data.sequence = NULL;

  // Create the thread
  if (pthread_create(&thread, NULL, generate_fibonacci, &data) != 0) {
    perror("Failed to create thread");
    return 1;
  }

  // Wait for the thread to finish
  if (pthread_join(thread, NULL) != 0) {
    perror("Failed to join thread");
    return 1;
  }

  // Print the generated sequence
  printf("Fibonacci Sequence: %lli", data.sequence[0]);
  for (int i = 1; i < data.count; i++)
    printf(" %lli", data.sequence[i]);

  puts("");

  // Clean up allocated memory
  free(data.sequence);

  return 0;
}
